version: '3'
services:
    server:
        build: .
        ports:
            - "8000:8000"
        command: python /opt/main.py
        depends_on:
            - redis
        environment:
            HOST: '0.0.0.0'
            PORT: 8000
            REDIS_PORT: 6379

    redis:
        image: "redis:latest"
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]

